# These are supported funding model platforms

github: [inouehost] # GitHub Sponsors username
patreon: # (kosong karena tidak ada)
open_collective: # (kosong karena tidak ada)
ko_fi: # (kosong karena tidak ada)
tidelift: # (kosong karena tidak ada)
community_bridge: inouehost # Community Bridge project name
liberapay: # (kosong karena tidak ada)
issuehunt: # (kosong karena tidak ada)
lfx_crowdfunding: # (kosong karena tidak ada)
polar: # (kosong karena tidak ada)
buy_me_a_coffee: # (kosong karena tidak ada)
thanks_dev: # (kosong karena tidak ada)
custom: 
  - "https://chat.whatsapp.com/C7XqPD1EXZf4Js2kK5hR8n?mode=ems_copy_t"
  - "https://ai-inouehost.my.id/donate"
